### ISSUE TITLE
Doesn't work with Vue 2.4

### ISSUE THREAD

**Issue by jzelez** [fergaldoyle/vue-form#74]
Throws error on init somewhere in Vue code.
`TypeError: parentVal.call is not a function`

I've tried with the example provided in README, just replaced vue.js for a 2.4.1 version.
https://jsfiddle.net/bqys2p5y/15/

**Comment by mkelley82** [comment]
I'm experiencing the same issue.

**Comment by fergaldoyle** [comment]
Fixed with: https://github.com/fergaldoyle/vue-form/releases/tag/4.3.4

**Comment by jzelez** [comment]
Works now. Thanks!
